version: '3.8'

services:
  qt_gui_wrapper:
    build:
      context: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    working_dir: /app/qt_gui_wrapper/build
    command: ["./ImageProcessorGUI"] 

  python_cli_wrapper:
    build:
      context: .
    volumes:
      - ./output:/app/python_cli_wrapper/output
    working_dir: /app
    command: ["python3", "python_cli_wrapper/main.py", "--input-dir", "python_cli_wrapper/images/", "--transformation", "flip_x_axis","--transformation","grayscale","--output-dir", "./python_cli_wrapper/output"]


