version: '3.8'

services:
  qt_gui_wrapper:
    build:
      context: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    working_dir: /app/images/
    command: ["ImageProcessorGUI"] 

  python_wrappers:
    build:
      context: .
    volumes:
      - ./output:/app/python_wrappers/output
    working_dir: /app
    command: ["python3", "python_wrappers/cli_interface.py", "--input-dir", "/app/images", "--transformation", "flip_x_axis","--transformation","grayscale","--output-dir", "./python_wrappers/output"]

  python_rest_api:
    build:
      context: .
    working_dir: /app/python_wrappers
    ports:
      - 8000:8000
    command: ["python3", "rest_api.py"]

  typescript_web_ui:
    build:
      context: typescript_web_ui 
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_HOST=http://localhost:8000

