version: '3.8'

services:

  python_cli_wrapper:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./output:/app/python_cli_wrapper/output
    working_dir: /app
    command: ["python3", "python_cli_wrapper/main.py", "--input-dir", "python_cli_wrapper/images/", "--transformation-type", "flipped_grayscale", "--output-dir", "./python_cli_wrapper/output"]


