name: Build, Push, and Release Debian Package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master jobs:

  build-test-deploy:
    runs-on: ubuntu-20.04

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx (for multi-platform builds, if needed)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t surescan_image .

      - name: Run C++ googletests 
        run: docker run --rm surescan_image bash -c "export GTEST_OUTPUT='xml:/output/transformer_lib_test_results.xml';/app/cpp_image_transformers_library/transformer_library/build/unit_tests /app/images/sunflower.jpg;ls /output;"

      # Optionally, upload test results as an artifact
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: /output/transformer_lib_test_results.xml

      # Run the Docker container to build the Debian package
      - name: Build Debian Package
        run: docker run --rm -v ${{ github.workspace }}/output:/out surescan_image sh -c "cp /output/* /out"

      # Upload the .deb package as an artifact
      - name: Upload Debian Package
        uses: actions/upload-artifact@v3
        with:
          name: debian-package
          path: ./output/*.deb
